name: PROMPT_INPUT_Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prompt for FileName variable
        run: |
          echo "Please enter the value for FileName: "
          read FileName
          echo "You entered: $FileName"
    
