name: PROMPT_INPUT_Workflow

on: 
  workflow_dispatch:
    inputs:
      filename: 
      description: "Enter the file name:"
      default: hello
      required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prompt for FileName variable
        run: |
          excelfilename=${{github.event.inputs.filename}}"
          echo "You entered: ${{excelfilename}}
    
