name: READINPUTWorkflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt for Input
        run: echo "Please enter a value"
        shell: bash
      - name: Run My Command
        run: echo ${{ github.event.inputs.myinput }}
        env:
          MY_INPUT: ${{ github.event.inputs.myinput }}


    
