name: READINPUTWorkflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt for Input
        run: echo "Please enter a value"
        shell: bash
      - name: Run My Command
        run: |
          echo ${{ github.event.inputs.environment }}
          echo ${{ github.event.inputs.branch }}
        env:
          MY_ENV: ${{ github.event.inputs.environment }}
          MY_BR: ${{ github.event.inputs.branch }}


    
