name: READINPUTWorkflow

on: 
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter file name'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo Command
        env:
          FILE_NAME: ${{ github.event.inputs.filename }}
        run: |
          echo ${{ env.FILE_NAME }}
        


    
